#!/usr/bin/env bash

echo "Updating apt-get"
sudo apt-get update

echo "Installing nginx"
sudo apt-get install nginx

echo "Copying files"
sudo cp -r ./briw/* /var/www/html/briw

echo "Start the nginx server"
sudo service nginx restart
