---
- hosts: ec2
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest update_cache=yes
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the static website directory over to the remote machine
      copy:
        src: ~/Documents/academy/briw/website/
        dest: /var/www/html/briw
        directory_mode: yes
      become: yes
    - name: restart nginx
      service:
        name=nginx
        state=restarted
      become: yes
