main_menu_context = "Hello! What do you want to do today?"
people_menu = "View and edit registered users"
drinks_menu = "View and edit the available drinks list"
favourites_menu = "View or edit the registered users' favourite drinks"
rounds_menu = "Start a round, or join an existing round."
get_help = "I need help"
exit_ = "Exit"

help_menu_context = "Here's some information about the different main menu options:"
people_help = "You can see all the registered people, as well as add and remove people from the list of registered team members."
drinks_help = "View the list of available drinks, and add and remove drinks when your stock changes."
favourites_help = "Ensure that each registered user is assigned a favourite drink so that they can join rounds easily."
rounds_help = "Setup a new round and allow people to join and request their favourite drinks."
help_help = "That's what got you here!"
exit_help = "Exit this application and continue with your day"

menu_return = "Return to the main menu."
menu_return_enter = "Press 'enter' to return to the main menu."

people_menu_context = "People options:"
show_people = "Show the list of registered users."
add_people = "Add new people to the list of users."
remove_people = "Remove people from the list of users."
